version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: keuangan_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sintenbademundut 
      POSTGRES_DB: keuangan_rumah
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: keuangan_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:sintenbademundut@db:5432/keuangan_rumah?schema=public
      - NODE_ENV=production
      # - ORIGIN=https://domain-anda.com # Uncomment dan ganti dengan domain Anda jika diperlukan untuk SvelteKit Auth/CORS
    depends_on:
      - db
    # Command ini dijalankan saat container start: jalankan migrasi database lalu jalankan aplikasi
    command: sh -c "npx prisma migrate deploy && node build/index.js"

volumes:
  pgdata:
